spring.application.name=project

spring.datasource.url=jdbc:mysql://localhost:3307/chat_support_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update


jwt.secret=queue_ticket_VSJh3Txkgi9rE6VWApPihkZj52yAETiT4dK5ugOz5eZC7H71QgUnlNL/1DUpjZsgRugfhXv8KCNB/FIpR+jWmQ